node {

    // Define variables
    def APP_NAME = "salary-api"
    def REPORT_DIR = "trivy-reports"
    

    try {
    
        stage('Clean Workspace') {
            deleteDir()
        }
        stage('Setup Maven') {
        script {
            def mvnHome = tool name: 'Maven3', type: 'maven'
            env.PATH = "${mvnHome}/bin:${env.PATH}"
            }
        }
        stage('Checkout Code') {
            git url: 'https://github.com/mukeshdevelp/ot-microservice-sarthi.git', branch: 'backend'
        }

        stage('Set Java 17 Environment') {
            script {
                env.JAVA_HOME = "/usr/lib/jvm/java-17-openjdk-amd64"
                env.PATH = "${env.JAVA_HOME}/bin:${env.PATH}"
            }
        }

        stage('Verify Java') {
            sh '''
                echo "JAVA_HOME=$JAVA_HOME"
                which java
                which javac
                java -version
                javac -version
            '''
        }

       stage('Install Trivy') {
    sh '''
        if ! command -v trivy &> /dev/null
        then
            echo "Installing Trivy locally..."

            TRIVY_VERSION=$(curl -s https://api.github.com/repos/aquasecurity/trivy/releases/latest | grep tag_name | cut -d '"' -f 4 | sed 's/v//')

            echo "Latest Trivy version: $TRIVY_VERSION"

            wget -q https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz

            tar -xzf trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz

            chmod +x trivy

            mkdir -p $HOME/bin
            mv trivy $HOME/bin/trivy

            echo "Installed at $HOME/bin/trivy"
        else
            echo "Trivy already installed"
        fi
        '''
        }   
        stage('Add Trivy to PATH') {
         script {
            env.PATH = "${env.HOME}/bin:${env.PATH}"
            }
        }

        stage('Verify Trivy Installation') {
            sh '''
                trivy --version
            '''
        }

        stage('Build Maven Project') {
            sh '''
                ls
                pwd
                cd salary/salary-api/
                mvn clean package -DskipTests
            '''
        }

        stage('Create Report Directory') {
            sh """
                mkdir -p ${REPORT_DIR}
            """
        }

        stage('Trivy Filesystem Scan (Table Output)') {
            sh """
                trivy fs .
            """
        }

        stage('Generate JSON Report') {
            sh """
                trivy fs -f json -o ${REPORT_DIR}/trivy-report.json .
            """
        }

        stage('Generate SARIF Report') {
            sh """
                trivy fs --format sarif -o ${REPORT_DIR}/trivy-report.sarif .
            """
        }

        stage('Cleanup') {
            sh "ls -lh ${REPORT_DIR}"
        }

    } catch (err) {
        // Slack notification for failure
        slackSend(
            channel: '#ci-operation-notifications',
            color: 'danger',
            message: """
            Build Failed

            Job: ${env.JOB_NAME}
            Build: #${env.BUILD_NUMBER}
            URL: ${env.BUILD_URL}
            """
        )
        error "Pipeline failed: ${err}"
    } finally {
        if (currentBuild.currentResult == 'SUCCESS') {
            slackSend(
                channel: '#ci-operation-notifications',
                color: 'good',
                message: """
                //Build Successful

                Job: ${env.JOB_NAME}
                Build: #${env.BUILD_NUMBER}
                URL: ${env.BUILD_URL}
                """
            )
        }
        // Always archive artifacts
        archiveArtifacts artifacts: "${REPORT_DIR}/*", fingerprint: true
    }
}