pipeline {

    agent any

    environment {
        TARGET_URL = "http://34.239.167.247:8081/"
        ZAP_PORT = "8090"
        ZAP_API_KEY = "attendancekey"
        REPORT_DIR = "zap-reports"
        ZAP_DIR = "zap"
    }
   
    stages {
        stage('Clean Workspace') {
            steps {
                deleteDir()
            }
        }
        stage('Setup Java 17') {
            steps {
                sh '''
                    echo "Downloading Java 17..."

                    mkdir -p java
                    cd java

                    wget -q https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.12+7/OpenJDK17U-jdk_x64_linux_hotspot_17.0.12_7.tar.gz

                    tar -xzf OpenJDK17U-jdk_x64_linux_hotspot_17.0.12_7.tar.gz

                    echo "Java extracted"
                    ls -l
                '''
            }
        }

        

        stage('Download OWASP ZAP') {
            steps {
                sh '''
                    echo "Downloading portable ZAP..."

                    mkdir -p $ZAP_DIR
                    cd $ZAP_DIR

                    wget -q https://github.com/zaproxy/zaproxy/releases/download/v2.17.0/ZAP_2.17.0_Linux.tar.gz

                    tar -xzf ZAP_2.17.0_Linux.tar.gz

                    echo "ZAP extracted"
                    ls -l
                '''
            }
        }
        stage('Debug Workspace') {
            steps {
                sh '''
                    echo "Listing workspace..."
                    ls -R
                '''
            }
        }
        stage('Start ZAP') {
            steps {
                sh '''
                    echo "Setting Java 17..."

                    # Find extracted Java directory
                    JAVA_DIR=$(ls -d java/jdk-17* | head -n 1)

                    export JAVA_HOME=$PWD/$JAVA_DIR
                    export PATH=$JAVA_HOME/bin:$PATH

                    echo "Using JAVA_HOME=$JAVA_HOME"
                    java -version

                    echo "Starting ZAP..."

                    nohup $ZAP_DIR/ZAP_2.17.0/zap.sh -daemon \
                        -port $ZAP_PORT \
                        -host 127.0.0.1 \
                        -config api.key=$ZAP_API_KEY \
                        > zap.log 2>&1 &

                    echo "Waiting for ZAP..."

                    for i in {1..12}
                    do
                        sleep 5
                        curl -s http://127.0.0.1:$ZAP_PORT >/dev/null && echo "ZAP is UP" && exit 0
                        echo "Waiting..."
                    done

                    echo "ZAP failed"
                    cat zap.log
                    exit 1
                '''
            }
        }

        stage('Run Spider Scan') {
            steps {
                sh """
                    echo "Running Spider Scan..."
                    curl "http://127.0.0.1:${ZAP_PORT}/JSON/spider/action/scan/?url=${TARGET_URL}&apikey=${ZAP_API_KEY}"
                """
            }
        }
        stage('Access Target Endpoint') {
    steps {
        sh """
            echo "Accessing API so ZAP can register it..."

            curl -x http://127.0.0.1:${ZAP_PORT} \
            http://34.239.167.247:8081/attendance/search/all
        """
    }
}
        stage('Run Active Scan') {
    steps {
        sh """
            echo "Running Active Scan..."

            curl "http://127.0.0.1:${ZAP_PORT}/JSON/ascan/action/scan/?url=http://34.239.167.247:8081/attendance/search/all&apikey=${ZAP_API_KEY}"
        """
    }
}

        stage('Generate Report') {
            steps {
                sh """
                    mkdir -p ${REPORT_DIR}

                    echo "Generating report..."
                    curl "http://127.0.0.1:${ZAP_PORT}/OTHER/core/other/htmlreport/?apikey=${ZAP_API_KEY}" \
                    -o ${REPORT_DIR}/zap_attendance_report.html
                """
            }
        }

        stage('Archive Report') {
            steps {
                archiveArtifacts artifacts: "${REPORT_DIR}/*.html", fingerprint: true
            }
        }
    }

    post {
        always {
            echo "Cleaning up ZAP..."
            sh """
                pkill -f zap.sh || true
                rm -rf ${ZAP_DIR} || true
            """
        }
    }
}